// apps/svelte/src/pages/Directions.svelte
<script lang="ts">
  // Directions.svelte — click map to set origin/destination, then display route.
  //
  // Imports from: @gebeta/js (GebetaMaps via Map.svelte context)
  // The DirectionsManager is accessed via gebetaMap.getDirections() / displayRoute() after init.
  // Intentionally does NOT import GeocodingManager, ClusteringManager, FenceManager, NavigationManager.

  import Map, { type Platform } from '../lib/Map.svelte';
  import { authParam } from '../lib/config';
  import '../lib/panel.css';
  import type { GebetaMaps } from '@gebeta/js';
  import type { API } from '@gebeta/api';

  const ORIGIN_ICON = 'https://cdn-icons-png.flaticon.com/512/1828/1828640.png';
  const DEST_ICON = 'https://cdn-icons-png.flaticon.com/512/3081/3081559.png';

  let mode = $state<'origin' | 'destination' | null>(null);
  let originCoords = $state<{ lat: number; lng: number } | null>(null);
  let destCoords = $state<{ lat: number; lng: number } | null>(null);
  let routeDistance = $state<string | number | null | undefined>(null);
  let routeDuration = $state<string | number | null | undefined>(null);
  let showRoute = $state(false);
  let loading = $state(false);

  let gebetaMapRef: GebetaMaps | null = null;
  let platformRef: Platform | null = null;
  let originMarker: ReturnType<Platform['markerFactory']['createMarker']> = null;
  let destMarker: ReturnType<Platform['markerFactory']['createMarker']> = null;

  const canGetDirections = $derived(!!originCoords && !!destCoords && !loading);

  function addPinMarker(lng: number, lat: number, iconUrl: string) {
    return platformRef!.markerFactory.createMarker({ imageUrl: iconUrl, size: [30, 30] })
      ?.setLngLat({ lng, lat })
      .addTo(platformRef!.mapAdapter);
  }

  function handleReady(gm: GebetaMaps, _m: unknown, platform: Platform) {
    gebetaMapRef = gm;
    platformRef = platform;

    platform.mapAdapter.on('click', (...args: unknown[]) => {
      const e = args[0] as { lngLat: API.Common.Types.LngLat };
      const { lat, lng } = e.lngLat;
      if (mode === 'origin') {
        originMarker?.remove();
        originMarker = addPinMarker(lng, lat, ORIGIN_ICON);
        originCoords = { lat, lng };
        mode = null;
      } else if (mode === 'destination') {
        destMarker?.remove();
        destMarker = addPinMarker(lng, lat, DEST_ICON);
        destCoords = { lat, lng };
        mode = null;
      }
    });
  }

  async function getDirections() {
    if (!gebetaMapRef || !originCoords || !destCoords) return;
    loading = true;
    try {
      const routeData = await gebetaMapRef.getDirections(originCoords, destCoords, {});
      gebetaMapRef.displayRoute(routeData, { showMarkers: false });
      routeDistance = routeData.distance;
      routeDuration = routeData.duration;
      showRoute = true;
    } catch (err: unknown) {
      alert('Directions failed: ' + String(err instanceof Error ? err.message : err));
    } finally {
      loading = false;
    }
  }

  function clearRoute() {
    gebetaMapRef?.clearRoute();
    showRoute = false;
    routeDistance = null;
    routeDuration = null;
  }

  function clearMarkers() {
    originMarker?.remove(); originMarker = null;
    destMarker?.remove(); destMarker = null;
    originCoords = null;
    destCoords = null;
    clearRoute();
  }
</script>

<div class="page">
  <Map auth={authParam} center={[38.7685, 9.0161]} zoom={12} onready={handleReady}>
    {#snippet children()}
      <div class="control-panel">
        <h3>Directions</h3>
        <div style="display: flex; gap: 8px; margin-bottom: 8px;">
          <button
            class={mode === 'origin' ? 'primary' : ''}
            style="flex: 1;"
            onclick={() => { mode = mode === 'origin' ? null : 'origin'; }}
          >Set Origin</button>
          <button
            class={mode === 'destination' ? 'primary' : ''}
            style="flex: 1;"
            onclick={() => { mode = mode === 'destination' ? null : 'destination'; }}
          >Set Destination</button>
        </div>
        <div class="coords-box">
          <div><strong>Origin:</strong> {originCoords ? `${originCoords.lat.toFixed(5)}, ${originCoords.lng.toFixed(5)}` : 'Not set'}</div>
          <div><strong>Destination:</strong> {destCoords ? `${destCoords.lat.toFixed(5)}, ${destCoords.lng.toFixed(5)}` : 'Not set'}</div>
        </div>
        <button class="primary" onclick={getDirections} disabled={!canGetDirections}>
          {loading ? 'Loading...' : 'Get Directions'}
        </button>
        <button onclick={clearRoute}>Clear Route</button>
        <button onclick={clearMarkers}>Clear Points</button>
        {#if showRoute}
          <div class="route-info">
            <strong>Route</strong>
            {#if routeDistance}<p>Distance: {routeDistance}</p>{/if}
            {#if routeDuration}<p>Duration: {routeDuration}</p>{/if}
          </div>
        {/if}
        <p class="hint">
          Click "Set Origin", then click the map.<br />
          Then "Set Destination" and click the map.<br />
          Use "Get Directions" to show the route.
        </p>
      </div>
    {/snippet}
  </Map>
</div>

<style>
  .page { width: 100%; height: 100%; position: relative; }
</style>

// apps/react/src/pages/Directions.tsx
// Directions.tsx — click map to set origin/destination, then display route.
// Accesses DirectionsManager via gebetaMap.getDirections() / displayRoute() after onReady.

import { useRef, useState, useCallback } from 'react';
import Map, { type Platform } from '../Map';
import { auth } from '../config';
import type { GebetaMaps } from '@gebeta/js';
import type { Map as MapLibreMap } from 'maplibre-gl';
import type { API } from '@gebeta/api';
import '../panel.css';

const ORIGIN_ICON = 'https://cdn-icons-png.flaticon.com/512/1828/1828640.png';
const DEST_ICON = 'https://cdn-icons-png.flaticon.com/512/3081/3081559.png';

type Marker = ReturnType<Platform['markerFactory']['createMarker']>;
type LngLat = { lat: number; lng: number };

export default function Directions() {
  const [mode, setMode] = useState<'origin' | 'destination' | null>(null);
  const [origin, setOrigin] = useState<LngLat | null>(null);
  const [dest, setDest] = useState<LngLat | null>(null);
  const [routeInfo, setRouteInfo] = useState<{
    distance?: string | number;
    duration?: string | number;
  } | null>(null);
  const [loading, setLoading] = useState(false);

  const gebetaMapRef = useRef<GebetaMaps | null>(null);
  const platformRef = useRef<Platform | null>(null);
  const originMarkerRef = useRef<Marker>(null);
  const destMarkerRef = useRef<Marker>(null);
  const modeRef = useRef(mode);
  modeRef.current = mode;

  function addPinMarker(platform: Platform, lng: number, lat: number, iconUrl: string): Marker {
    return (
      platform.markerFactory
        .createMarker({ imageUrl: iconUrl, size: [30, 30] })
        ?.setLngLat({ lng, lat })
        .addTo(platform.mapAdapter) ?? null
    );
  }

  function handleReady(gm: GebetaMaps, _m: MapLibreMap, platform: Platform) {
    gebetaMapRef.current = gm;
    platformRef.current = platform;
    platform.mapAdapter.on('click', (...args: unknown[]) => {
      const e = args[0] as { lngLat: API.Common.Types.LngLat };
      const { lat, lng } = e.lngLat;
      if (modeRef.current === 'origin') {
        originMarkerRef.current?.remove();
        originMarkerRef.current = addPinMarker(platform, lng, lat, ORIGIN_ICON);
        setOrigin({ lat, lng });
        setMode(null);
      } else if (modeRef.current === 'destination') {
        destMarkerRef.current?.remove();
        destMarkerRef.current = addPinMarker(platform, lng, lat, DEST_ICON);
        setDest({ lat, lng });
        setMode(null);
      }
    });
  }

  const getDirections = useCallback(async () => {
    if (!gebetaMapRef.current || !origin || !dest) return;
    setLoading(true);
    try {
      const routeData = await gebetaMapRef.current.getDirections(origin, dest, {});
      gebetaMapRef.current.displayRoute(routeData, { showMarkers: false });
      setRouteInfo({ distance: routeData.distance, duration: routeData.duration });
    } catch (err) {
      alert('Directions failed: ' + String(err instanceof Error ? err.message : err));
    } finally {
      setLoading(false);
    }
  }, [origin, dest]);

  const clearRoute = useCallback(() => {
    gebetaMapRef.current?.clearRoute();
    setRouteInfo(null);
  }, []);

  const clearAll = useCallback(() => {
    originMarkerRef.current?.remove();
    originMarkerRef.current = null;
    destMarkerRef.current?.remove();
    destMarkerRef.current = null;
    setOrigin(null);
    setDest(null);
    clearRoute();
  }, [clearRoute]);

  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      <Map auth={auth} center={[38.7685, 9.0161]} zoom={12} onReady={handleReady}>
        <div className="control-panel">
          <h3>Directions</h3>
          <div style={{ display: 'flex', gap: 8, marginBottom: 8 }}>
            <button
              className={mode === 'origin' ? 'primary' : ''}
              style={{ flex: 1 }}
              onClick={() => setMode(m => (m === 'origin' ? null : 'origin'))}
            >
              Set Origin
            </button>
            <button
              className={mode === 'destination' ? 'primary' : ''}
              style={{ flex: 1 }}
              onClick={() => setMode(m => (m === 'destination' ? null : 'destination'))}
            >
              Set Destination
            </button>
          </div>
          <div className="coords-box">
            <div>
              <strong>Origin:</strong>{' '}
              {origin ? `${origin.lat.toFixed(5)}, ${origin.lng.toFixed(5)}` : 'Not set'}
            </div>
            <div>
              <strong>Destination:</strong>{' '}
              {dest ? `${dest.lat.toFixed(5)}, ${dest.lng.toFixed(5)}` : 'Not set'}
            </div>
          </div>
          <button
            className="primary"
            onClick={getDirections}
            disabled={!origin || !dest || loading}
          >
            {loading ? 'Loading...' : 'Get Directions'}
          </button>
          <button onClick={clearRoute}>Clear Route</button>
          <button onClick={clearAll}>Clear Points</button>
          {routeInfo && (
            <div className="route-info">
              <strong>Route</strong>
              {routeInfo.distance != null && <p>Distance: {routeInfo.distance}</p>}
              {routeInfo.duration != null && <p>Duration: {routeInfo.duration}</p>}
            </div>
          )}
          <p className="hint">
            Click "Set Origin", then click the map.
            <br />
            Then "Set Destination" and click the map.
            <br />
            Use "Get Directions" to show the route.
          </p>
        </div>
      </Map>
    </div>
  );
}
