// apps/react/src/pages/Geocoding.tsx
// Geocoding.tsx — forward and reverse geocoding example.
// Accesses GeocodingManager via gebetaMap.geocodingManager after onReady.

import { useRef, useState, useCallback } from 'react';
import Map, { type Platform } from '../Map';
import { auth } from '../config';
import type { GebetaMaps } from '@gebeta/js';
import type { Map as MapLibreMap } from 'maplibre-gl';
import type { API } from '@gebeta/api';
import '../panel.css';

type Marker = API.Platform.Types.IMarker;
type Result = { name: string; lat: number; lng: number };

export default function Geocoding() {
  const [placeInput, setPlaceInput] = useState('');
  const [latInput, setLatInput] = useState('');
  const [lngInput, setLngInput] = useState('');
  const [results, setResults] = useState<Result[]>([]);
  const [ready, setReady] = useState(false);

  const gebetaMapRef = useRef<GebetaMaps | null>(null);
  const platformRef = useRef<Platform | null>(null);
  const markersRef = useRef<Marker[]>([]);

  function handleReady(gm: GebetaMaps, _m: MapLibreMap, platform: Platform) {
    gebetaMapRef.current = gm;
    platformRef.current = platform;
    setReady(true);
  }

  function clearResultMarkers() {
    markersRef.current.forEach(mk => mk.remove());
    markersRef.current = [];
  }

  function showResults(items: Array<{ name?: string; lngLat?: { lat: number; lng: number } }>) {
    clearResultMarkers();
    const mapped = items
      .filter(i => i.lngLat != null)
      .map(i => ({ name: i.name ?? 'Unknown', lat: i.lngLat!.lat, lng: i.lngLat!.lng }));
    setResults(mapped);
    const platform = platformRef.current;
    if (!platform) return;
    mapped.forEach(r => {
      const mk = platform.markerFactory
        .createMarker({})
        ?.setLngLat({ lat: r.lat, lng: r.lng })
        .addTo(platform.mapAdapter);
      if (mk) markersRef.current.push(mk);
    });
    if (mapped[0]) {
      platform.mapAdapter.easeTo({ center: [mapped[0].lng, mapped[0].lat], zoom: 14 });
    }
  }

  const doGeocode = useCallback(async () => {
    if (!ready || !gebetaMapRef.current || !placeInput.trim()) return;
    try {
      const res = await gebetaMapRef.current.geocodingManager.geocode(placeInput.trim());
      showResults(res ?? []);
    } catch (err) {
      setResults([]);
      alert('Geocoding failed: ' + String(err instanceof Error ? err.message : err));
    }
  }, [ready, placeInput]);

  const doReverseGeocode = useCallback(async () => {
    if (!ready || !gebetaMapRef.current) return;
    const lat = parseFloat(latInput);
    const lng = parseFloat(lngInput);
    if (isNaN(lat) || isNaN(lng)) {
      alert('Enter valid latitude and longitude.');
      return;
    }
    try {
      const res = await gebetaMapRef.current.geocodingManager.reverseGeocode({ lat, lng });
      showResults(res ?? []);
    } catch (err) {
      setResults([]);
      alert('Reverse geocoding failed: ' + String(err instanceof Error ? err.message : err));
    }
  }, [ready, latInput, lngInput]);

  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      <Map auth={auth} center={[38.7685, 9.0161]} zoom={12} onReady={handleReady}>
        <div className="control-panel">
          <h3>Geocoding</h3>
          <h4>Forward (search by name)</h4>
          <input
            type="text"
            value={placeInput}
            onChange={e => setPlaceInput(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && doGeocode()}
            placeholder="e.g. Bole, Addis Ababa"
          />
          <button className="primary" onClick={doGeocode} disabled={!ready}>
            Search
          </button>
          <h4>Reverse (search by coordinates)</h4>
          <input
            type="number"
            value={latInput}
            onChange={e => setLatInput(e.target.value)}
            placeholder="Latitude"
          />
          <input
            type="number"
            value={lngInput}
            onChange={e => setLngInput(e.target.value)}
            placeholder="Longitude"
          />
          <button className="primary" onClick={doReverseGeocode} disabled={!ready}>
            Find address
          </button>
          <h4>Results</h4>
          <div className="result-list">
            {results.length === 0 ? (
              <div style={{ padding: 8, color: '#888' }}>No results yet.</div>
            ) : (
              results.map(r => (
                <div
                  key={`${r.lat},${r.lng}`}
                  className="result-item"
                  onClick={() =>
                    platformRef.current?.mapAdapter.easeTo({ center: [r.lng, r.lat], zoom: 16 })
                  }
                >
                  <strong>{r.name}</strong>
                  <br />
                  <span style={{ color: '#666' }}>
                    {r.lat.toFixed(5)}, {r.lng.toFixed(5)}
                  </span>
                </div>
              ))
            )}
          </div>
        </div>
      </Map>
    </div>
  );
}

// apps/svelte/src/pages/Geocoding.svelte
<script lang="ts">
  // Geocoding.svelte — forward and reverse geocoding example.
  //
  // Imports from: @gebeta/js (GebetaMaps via Map.svelte's onready callback)
  // The GeocodingManager is accessed via gebetaMap.geocodingManager after style.load.
  // Intentionally does NOT import DirectionsManager, ClusteringManager, FenceManager, NavigationManager.

  import Map from '../lib/Map.svelte';
  import { authParam } from '../lib/config';
  import '../lib/panel.css';
  import type { GebetaMaps } from '@gebeta/js';
  import type { Platform } from '../lib/Map.svelte';

  let placeInput = $state('');
  let latInput = $state('');
  let lonInput = $state('');
  let results: Array<{ name: string; lat: number; lng: number }> = $state([]);
  let resultMarkers: API.Platform.Types.IMarker[] = [];
  let mapReady = $state(false);
  let platformRef: Platform | null = null;
  let gebetaMapRef: GebetaMaps | null = null;

  // @gebeta/api provides all the types we need — no maplibre-gl import required.
  import type { API } from '@gebeta/api';

  function handleReady(gm: GebetaMaps, _m: unknown, platform: Platform) {
    gebetaMapRef = gm;
    platformRef = platform;
    mapReady = true;
  }

  function clearResultMarkers() {
    resultMarkers.forEach((mk) => mk.remove());
    resultMarkers = [];
  }

  function showResults(items: Array<{ name?: string; lngLat?: { lat: number; lng: number } }>) {
    clearResultMarkers();
    results = items
      .filter((i) => i.lngLat != null)
      .map((i) => ({
        name: i.name ?? 'Unknown',
        lat: i.lngLat!.lat,
        lng: i.lngLat!.lng,
      }));

    if (!platformRef) return;
    results.forEach((r) => {
      const mk = platformRef!.markerFactory.createMarker({})?.setLngLat({ lat: r.lat, lng: r.lng }).addTo(platformRef!.mapAdapter);
      if (mk) resultMarkers.push(mk);
    });
    if (results[0]) {
      platformRef.mapAdapter.easeTo({ center: [results[0].lng, results[0].lat], zoom: 14 });
    }
  }

  function flyToResult(r: { lat: number; lng: number }) {
    platformRef?.mapAdapter.easeTo({ center: [r.lng, r.lat], zoom: 16 });
  }

  async function doGeocode() {
    if (!mapReady || !gebetaMapRef) return;
    if (!placeInput.trim()) { alert('Enter a place name.'); return; }
    try {
      const res = await gebetaMapRef.geocodingManager.geocode(placeInput.trim());
      showResults(res ?? []);
    } catch (err: unknown) {
      showResults([]);
      alert('Geocoding failed: ' + String(err instanceof Error ? err.message : err));
    }
  }

  async function doReverseGeocode() {
    if (!mapReady || !gebetaMapRef) return;
    const lat = parseFloat(latInput);
    const lon = parseFloat(lonInput);
    if (isNaN(lat) || isNaN(lon)) { alert('Enter valid latitude and longitude.'); return; }
    try {
      const res = await gebetaMapRef.geocodingManager.reverseGeocode({ lat, lng: lon });
      showResults(res ?? []);
    } catch (err: unknown) {
      showResults([]);
      alert('Reverse geocoding failed: ' + String(err instanceof Error ? err.message : err));
    }
  }
</script>

<div class="page">
  <Map auth={authParam} center={[38.7685, 9.0161]} zoom={12} onready={handleReady}>
    {#snippet children()}
      <div class="control-panel">
        <h3>Geocoding</h3>
        <h4>Forward (search by name)</h4>
        <input type="text" bind:value={placeInput} placeholder="e.g. Bole, Addis Ababa" />
        <button class="primary" onclick={doGeocode} disabled={!mapReady}>Search</button>

        <h4>Reverse (search by coordinates)</h4>
        <input type="number" bind:value={latInput} placeholder="Latitude" step="any" />
        <input type="number" bind:value={lonInput} placeholder="Longitude" step="any" />
        <button class="primary" onclick={doReverseGeocode} disabled={!mapReady}>Find address</button>

        <h4>Results</h4>
        <div class="result-list">
          {#if results.length === 0}
            <div style="padding: 8px; color: #888;">No results yet.</div>
          {:else}
            {#each results as r}
              <div
                class="result-item"
                onclick={() => flyToResult(r)}
                role="button"
                tabindex="0"
                onkeydown={(e) => e.key === 'Enter' && flyToResult(r)}
              >
                <strong>{r.name}</strong><br />
                <span style="color: #666;">{r.lat.toFixed(5)}, {r.lng.toFixed(5)}</span>
              </div>
            {/each}
          {/if}
        </div>
      </div>
    {/snippet}
  </Map>
</div>

<style>
  .page {
    width: 100%;
    height: 100%;
    position: relative;
  }
</style>
