// apps/react-native/src/pages/Navigation.tsx
/**
 * Navigation demo — turn-by-turn along a route with a simulated GPS driver.
 *
 * Flow: tap Set Origin/Dest → tap map → Get Route (draws it) → Start. A simulated location
 * provider walks the route coordinates; the NavigationManager moves the location marker, follows
 * with a driver-POV camera, and emits progress/step/arrive events shown in the panel.
 *
 * (Real device GPS would use `platform.locationProvider` instead of the simulator — but an
 * emulator has no moving fix, so the demo simulates movement along the fetched route.)
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import {
  GebetaMap,
  useGebetaMapContextOrNull,
  useDirections,
  useNavigation,
  createSimulatedLocationProvider,
} from '@gebeta/react-native';
import type { API } from '@gebeta/api';
import { authProps, type Auth } from '../config';

const ORIGIN_ICON = 'https://cdn-icons-png.flaticon.com/512/1828/1828640.png';
const DEST_ICON = 'https://cdn-icons-png.flaticon.com/512/3081/3081559.png';

type LngLat = API.Common.Types.LngLat;
type RouteData = API.Routing.Types.RouteData;

export default function Navigation({ auth }: { auth: Auth }) {
  return (
    <GebetaMap
      {...authProps(auth)}
      center={[38.7685, 9.0161]}
      zoom={13}
      style={styles.map}
    >
      <NavigationPanel auth={auth} />
    </GebetaMap>
  );
}

function NavigationPanel({ auth }: { auth: Auth }) {
  const ctx = useGebetaMapContextOrNull();
  const platform = ctx?.platform ?? null;
  const { directions } = useDirections(authProps(auth));
  const { navigation, isNavigating, progress, arrived } = useNavigation(
    authProps(auth),
    {
      autoReroute: true,
    },
  );

  const [mode, setMode] = useState<'origin' | 'destination' | null>(null);
  const [origin, setOrigin] = useState<LngLat | null>(null);
  const [dest, setDest] = useState<LngLat | null>(null);
  const [route, setRoute] = useState<RouteData | null>(null);
  const [loading, setLoading] = useState(false);

  const modeRef = useRef(mode);
  modeRef.current = mode;
  const speedRef = useRef(4);

  type Marker = ReturnType<
    NonNullable<typeof platform>['markerFactory']['createMarker']
  >;
  const originMarkerRef = useRef<Marker>(null);
  const destMarkerRef = useRef<Marker>(null);

  const dropMarker = useCallback(
    (lng: number, lat: number, iconUrl: string): Marker => {
      if (!platform) return null;
      return (
        platform.markerFactory
          .createMarker({ imageUrl: iconUrl, size: [30, 30], anchor: 'bottom' })
          ?.setLngLat({ lng, lat })
          .addTo(platform.mapAdapter) ?? null
      );
    },
    [platform],
  );

  // Pick origin/dest by tapping the map.
  useEffect(() => {
    if (!platform) return;
    const onClick = (...args: unknown[]) => {
      if (navigation?.isNavigating()) return;
      const e = args[0] as { lngLat: LngLat };
      const point = { lat: e.lngLat.lat, lng: e.lngLat.lng };
      if (modeRef.current === 'origin') {
        originMarkerRef.current?.remove();
        originMarkerRef.current = dropMarker(point.lng, point.lat, ORIGIN_ICON);
        setOrigin(point);
        setMode(null);
      } else if (modeRef.current === 'destination') {
        destMarkerRef.current?.remove();
        destMarkerRef.current = dropMarker(point.lng, point.lat, DEST_ICON);
        setDest(point);
        setMode(null);
      }
    };
    platform.mapAdapter.on('click', onClick);
    return () => {
      platform.mapAdapter.off('click', onClick);
    };
  }, [platform, dropMarker, navigation]);

  const getRoute = useCallback(async () => {
    if (!directions || !origin || !dest) return;
    setLoading(true);
    try {
      const r = await directions.getDirections(origin, dest, {});
      directions.displayRoute(r, { showMarkers: false });
      setRoute(r);
    } catch (err) {
      console.warn(
        'Route failed:',
        err instanceof Error ? err.message : String(err),
      );
    } finally {
      setLoading(false);
    }
  }, [directions, origin, dest]);

  const startNav = useCallback(() => {
    if (!navigation || !route) return;
    const coords = route.geometry?.coordinates ?? [];
    if (coords.length < 2) return;
    const provider = createSimulatedLocationProvider(
      coords,
      () => speedRef.current,
    );
    navigation.start(route, { userId: `demo-${Date.now()}` }, provider);
  }, [navigation, route]);

  const stopNav = useCallback(() => navigation?.stop(), [navigation]);

  const clearAll = useCallback(() => {
    navigation?.stop();
    directions?.clearRoute();
    originMarkerRef.current?.remove();
    originMarkerRef.current = null;
    destMarkerRef.current?.remove();
    destMarkerRef.current = null;
    setOrigin(null);
    setDest(null);
    setRoute(null);
  }, [navigation, directions]);

  return (
    <View style={styles.panel}>
      <Text style={styles.title}>Navigation</Text>

      {!isNavigating ? (
        <>
          <View style={styles.row}>
            <Btn
              label="Set Origin"
              active={mode === 'origin'}
              onPress={() => setMode(m => (m === 'origin' ? null : 'origin'))}
            />
            <Btn
              label="Set Dest"
              active={mode === 'destination'}
              onPress={() =>
                setMode(m => (m === 'destination' ? null : 'destination'))
              }
            />
          </View>
          <View style={styles.row}>
            <Btn
              label={loading ? 'Routing…' : 'Get Route'}
              disabled={!origin || !dest || loading}
              onPress={getRoute}
            />
            <Btn label="Start" primary disabled={!route} onPress={startNav} />
            <Btn label="Clear" onPress={clearAll} />
          </View>
          {arrived && <Text style={styles.arrived}>✓ Arrived!</Text>}
          <Text style={styles.hint}>
            Set origin & destination, Get Route, then Start to simulate driving.
          </Text>
        </>
      ) : (
        <>
          {progress?.currentStep?.instruction && (
            <Text style={styles.instruction}>
              {progress.currentStep.instruction}
            </Text>
          )}
          <Text style={styles.meta}>
            {formatDistance(progress?.remainingDistance)} left ·{' '}
            {formatDuration(progress?.remainingDuration)}
          </Text>
          {progress?.progress != null && (
            <View style={styles.progressBar}>
              <View
                style={[
                  styles.progressFill,
                  { width: `${Math.min(progress.progress, 100)}%` },
                ]}
              />
            </View>
          )}
          <Btn label="Stop" onPress={stopNav} />
        </>
      )}
    </View>
  );
}

function formatDistance(meters?: number): string {
  if (meters == null) return '—';
  return meters >= 1000
    ? `${(meters / 1000).toFixed(1)} km`
    : `${Math.round(meters)} m`;
}

function formatDuration(duration?: number | string): string {
  if (duration == null) return '—';
  if (typeof duration === 'string') return duration;
  const min = Math.round(duration / 60);
  return min >= 1 ? `${min} min` : `${Math.round(duration)} s`;
}

function Btn({
  label,
  onPress,
  active,
  primary,
  disabled,
}: {
  label: string;
  onPress: () => void;
  active?: boolean;
  primary?: boolean;
  disabled?: boolean;
}) {
  return (
    <TouchableOpacity
      style={[
        styles.btn,
        (active || primary) && styles.btnActive,
        disabled && styles.btnDisabled,
      ]}
      onPress={onPress}
      disabled={disabled}
      activeOpacity={0.7}
    >
      <Text
        style={[styles.btnText, (active || primary) && styles.btnTextActive]}
      >
        {label}
      </Text>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  map: { flex: 1 },
  panel: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderRadius: 10,
    padding: 12,
    gap: 6,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  title: { fontSize: 16, fontWeight: '700' },
  row: { flexDirection: 'row', gap: 8 },
  instruction: { fontSize: 15, fontWeight: '600', color: '#111' },
  meta: { fontSize: 13, color: '#333' },
  arrived: { fontSize: 14, fontWeight: '700', color: '#2e7d32' },
  hint: { fontSize: 12, color: '#666' },
  progressBar: {
    height: 6,
    backgroundColor: '#eee',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: { height: 6, backgroundColor: '#007cbf' },
  btn: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 6,
    backgroundColor: '#eee',
    alignItems: 'center',
  },
  btnActive: { backgroundColor: '#007cbf' },
  btnDisabled: { opacity: 0.5 },
  btnText: { fontSize: 13, fontWeight: '600', color: '#333' },
  btnTextActive: { color: '#fff' },
});

// apps/svelte/src/pages/Navigation.svelte
<script lang="ts">
  // Navigation.svelte — real GPS turn-by-turn navigation using BrowserLocationProvider.
  //
  // Imports from: @gebeta/js/navigation (NavigationManager, BrowserLocationProvider via GebetaMaps.navigation getter)
  // Intentionally does NOT import GeocodingManager, DirectionsManager standalone, ClusteringManager, FenceManager.

  import { onDestroy } from 'svelte';
  import { BrowserLocationProvider } from '@gebeta/js/navigation';
  import Map from '../lib/Map.svelte';
  import { authParam } from '../lib/config';
  import '../lib/panel.css';
  import type { GebetaMaps } from '@gebeta/js';
  import type { Platform } from '../lib/Map.svelte';
  import type { API } from '@gebeta/api';

  const ORIGIN_ICON = 'https://cdn-icons-png.flaticon.com/512/1828/1828640.png';
  const DEST_ICON = 'https://cdn-icons-png.flaticon.com/512/3081/3081559.png';

  let mode = $state<'origin' | 'destination' | null>(null);
  let originCoords = $state<{ lat: number; lng: number } | null>(null);
  let destCoords = $state<{ lat: number; lng: number } | null>(null);
  let routeReady = $state(false);
  let isNavigating = $state(false);
  let navStatus = $state<'inactive' | 'active' | 'warning'>('inactive');
  let remainingDistance = $state<number | undefined>(undefined);
  let remainingDuration = $state<number | undefined>(undefined);
  let instruction = $state<string | undefined>(undefined);
  let progress = $state<number | undefined>(undefined);
  let loadingRoute = $state(false);
  let ready = $state(false);

  let gebetaMapRef: GebetaMaps | null = null;
  let platformRef: Platform | null = null;
  let originMarker: API.Platform.Types.IMarker | null = null;
  let destMarker: API.Platform.Types.IMarker | null = null;
  let routeData: unknown = null;
  let locationProvider: InstanceType<typeof BrowserLocationProvider> | null = null;

  const canGetRoute = $derived(!!originCoords && !!destCoords && !loadingRoute && !isNavigating);
  const canStart = $derived(routeReady && !isNavigating);

  function addPinMarker(lng: number, lat: number, iconUrl: string): API.Platform.Types.IMarker | null {
    return platformRef!.markerFactory.createMarker({ imageUrl: iconUrl, size: [30, 30] })
      ?.setLngLat({ lng, lat })
      .addTo(platformRef!.mapAdapter) ?? null;
  }

  function handleReady(gm: GebetaMaps, _m: unknown, platform: Platform) {
    gebetaMapRef = gm;
    platformRef = platform;
    ready = true;

    platform.mapAdapter.on('click', (...args: unknown[]) => {
      const e = args[0] as { lngLat: API.Common.Types.LngLat };
      const { lat, lng } = e.lngLat;
      if (mode === 'origin') {
        originMarker?.remove();
        originMarker = addPinMarker(lng, lat, ORIGIN_ICON);
        originCoords = { lat, lng };
        mode = null;
      } else if (mode === 'destination') {
        destMarker?.remove();
        destMarker = addPinMarker(lng, lat, DEST_ICON);
        destCoords = { lat, lng };
        mode = null;
      }
    });

    setupNavigationEvents(gm);
  }

  function setupNavigationEvents(gm: GebetaMaps) {
    gm.navigation.on('start', () => {
      isNavigating = true;
      navStatus = 'active';
    });

    gm.navigation.on('stop', () => {
      isNavigating = false;
      navStatus = 'inactive';
      locationProvider?.stop();
      locationProvider = null;
    });

    gm.navigation.on('progress', (event: Record<string, unknown>) => {
      remainingDistance = event.remainingDistance as number | undefined;
      remainingDuration = event.remainingDuration as number | undefined;
      progress = event.progress as number | undefined;
      if (event.currentStep) {
        const step = event.currentStep as Record<string, unknown>;
        instruction = step.instruction as string | undefined;
      }
    });

    gm.navigation.on('stepchange', (event: Record<string, unknown>) => {
      if (event.currentStep) {
        const step = event.currentStep as Record<string, unknown>;
        instruction = step.instruction as string | undefined;
      }
    });

    gm.navigation.on('offroute', () => {
      navStatus = 'warning';
    });

    gm.navigation.on('arrive', () => {
      alert('You have arrived at your destination!');
      stopNavigation();
    });

    gm.navigation.on('error', (err: unknown) => {
      console.error('Navigation error:', err);
      alert('Navigation error: ' + String(err instanceof Error ? err.message : err));
    });
  }

  async function getRoute() {
    if (!gebetaMapRef || !originCoords || !destCoords) return;
    loadingRoute = true;
    try {
      const data = await gebetaMapRef.getDirections(originCoords, destCoords, {});
      routeData = data;
      gebetaMapRef.displayRoute(data, { showMarkers: false });
      routeReady = true;
    } catch (err: unknown) {
      alert('Route failed: ' + String(err instanceof Error ? err.message : err));
    } finally {
      loadingRoute = false;
    }
  }

  function startNavigation() {
    if (!gebetaMapRef?.navigation || !routeData) return;
    if (!navigator.geolocation) {
      alert('Geolocation is not supported by your browser.');
      return;
    }
    locationProvider = BrowserLocationProvider.getInstance({ enableHighAccuracy: true });
    gebetaMapRef.navigation.start(
      routeData as Parameters<typeof gebetaMapRef.navigation.start>[0],
      { userId: `demo-user-${Date.now()}`, role: 'driver', precision: 'high' },
      locationProvider
    );
  }

  function stopNavigation() {
    gebetaMapRef?.navigation?.stop();
  }

  function clearAll() {
    if (isNavigating) stopNavigation();
    originMarker?.remove(); originMarker = null;
    destMarker?.remove(); destMarker = null;
    originCoords = null;
    destCoords = null;
    routeData = null;
    routeReady = false;
    gebetaMapRef?.clearRoute();
    remainingDistance = undefined;
    remainingDuration = undefined;
    instruction = undefined;
    progress = undefined;
  }

  onDestroy(() => {
    if (isNavigating) {
      try { gebetaMapRef?.navigation?.stop(); } catch { /* ignore */ }
    }
  });
</script>

<div class="page">
  <Map auth={authParam} center={[38.7685, 9.0161]} zoom={12} onready={handleReady}>
    {#snippet children()}
      <div class="control-panel">
        <h3>Navigation (GPS)</h3>
        <div style="display: flex; gap: 8px; margin-bottom: 8px;">
          <button
            class={mode === 'origin' ? 'primary' : ''}
            style="flex: 1;"
            onclick={() => { mode = mode === 'origin' ? null : 'origin'; }}
            disabled={isNavigating}
          >Set Origin</button>
          <button
            class={mode === 'destination' ? 'primary' : ''}
            style="flex: 1;"
            onclick={() => { mode = mode === 'destination' ? null : 'destination'; }}
            disabled={isNavigating}
          >Set Destination</button>
        </div>
        <div class="coords-box">
          <div><strong>Origin:</strong> {originCoords ? `${originCoords.lat.toFixed(5)}, ${originCoords.lng.toFixed(5)}` : 'Not set'}</div>
          <div><strong>Destination:</strong> {destCoords ? `${destCoords.lat.toFixed(5)}, ${destCoords.lng.toFixed(5)}` : 'Not set'}</div>
        </div>
        <button class="primary" onclick={getRoute} disabled={!canGetRoute}>
          {loadingRoute ? 'Loading...' : 'Get Route'}
        </button>
        <button class="primary" onclick={startNavigation} disabled={!canStart}>Start Navigation</button>
        <button onclick={stopNavigation} disabled={!isNavigating}>Stop Navigation</button>
        <button onclick={clearAll} disabled={!ready}>Clear All</button>

        {#if isNavigating || navStatus !== 'inactive'}
          <div class="nav-info" class:active={navStatus === 'active'} class:warning={navStatus === 'warning'}>
            <div>
              <strong>Status:</strong>
              <span class="status-indicator" class:active={navStatus === 'active'} class:warning={navStatus === 'warning'}></span>
              {navStatus === 'active' ? 'Navigating' : navStatus === 'warning' ? 'Off route' : 'Inactive'}
            </div>
            {#if remainingDistance !== undefined}
              <div><strong>Remaining:</strong> {(remainingDistance / 1000).toFixed(2)} km</div>
            {/if}
            {#if remainingDuration !== undefined}
              <div><strong>ETA:</strong> {Math.round(remainingDuration / 60)} min</div>
            {/if}
            {#if instruction}
              <div><strong>Instruction:</strong> {instruction}</div>
            {/if}
            {#if progress !== undefined}
              <div><strong>Progress:</strong> {progress.toFixed(1)}%</div>
            {/if}
          </div>
        {/if}

        <p class="hint">
          1. Set origin and destination<br />
          2. Get route<br />
          3. Start navigation (requires location permission)<br />
          <strong>High Precision:</strong> Uses WebSocket for real-time tracking
        </p>
      </div>
    {/snippet}
  </Map>
</div>

<style>
  .page { width: 100%; height: 100%; position: relative; }
</style>
